### ISSUE TITLE
Show/Hide toggle

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-OWI/owi-blog#108]
@mwernimont do you think you could add something like this to the blog theme:

http://jsfiddle.net/fyUJc/40/

So that we could wrap a chunk of R code (or whatever really) with a similar "hideMe" div?

For example, the code chunk a the bottom of this link:
http://dev-owi.usgs.gov-website.s3-website-us-west-2.amazonaws.com/blog/plotFlowConc/

might be interesting to some...but not to most.

**Comment by ldecicco-USGS** [comment]
We might want to recycle that in the training Hugo theme too

**Comment by mwernimont** [comment]
I can, but I'm a little swamped with tasks, huge priority or can it wait a bit?

**Comment by ldecicco-USGS** [comment]
it can wait

**Comment by mwernimont** [comment]
Assign it to me though

**Comment by ldecicco-USGS** [comment]
I took the work you did for the Previous/Next in the training to add this.
