### ISSUE TITLE
release two posts

### ISSUE THREAD

**Issue by jread-usgs** [USGS-OWI/owi-blog#117]
Not sure what this issue is supposed to look like @ldecicco-USGS but...

http://dev-owi.usgs.gov-website.s3-website-us-west-2.amazonaws.com/blog/leaflet/
http://dev-owi.usgs.gov-website.s3-website-us-west-2.amazonaws.com/blog/plotFlowConc/

**Comment by ldecicco-USGS** [comment]
Yup, just something to the effect of:

"Please change the status of the following posts to approved:

http://dev-owi.usgs.gov-website.s3-website-us-west-2.amazonaws.com/blog/leaflet/
http://dev-owi.usgs.gov-website.s3-website-us-west-2.amazonaws.com/blog/plotFlowConc/
"
That should notify people to take off the "draft: true" line on the md file, and make a push to prod. Clear as mud?

**Comment by jread-usgs** [comment]
ok, thanks. Please do that ☝️
