### ISSUE TITLE
Table css

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-OWI/owi-blog#123]
I'm guessing there will be need for static tables. @mwernimont got any fancy style you'd like to use?

http://dev-owi.usgs.gov-website.s3-website-us-west-2.amazonaws.com/blog/introduction/

**Comment by mwernimont** [comment]
![screen shot 2016-09-08 at 10 33 11 am](https://cloud.githubusercontent.com/assets/6390096/18355759/c81e4db4-75af-11e6-9cd1-315e74f9996b.png)

@ldecicco-USGS Nothing too fancy, but thought it looked a little more organized like this. #153 has the code if you like it

**Comment by ldecicco-USGS** [comment]
Perfect. That's what I was hoping, slightly better than default.
