### ISSUE TITLE
All posts on one page for home screen?

### ISSUE THREAD

**Issue by wdwatkins** [USGS-OWI/owi-blog#21]
I think its a bit odd having the listing of posts split between two pages, and would look better all on one that you can scroll through.  This might be a personal opinion though.

**Comment by ldecicco-USGS** [comment]
@mwernimont will look into the grid settings and see if there could be a better configuration

**Comment by mwernimont** [comment]
@ldecicco-USGS So made the pagination count 100 which allows the blogs to show up at once. I couldn't find a show all command for it so hence the 100. 

The theme has the first 4 blogs a little bigger than then rest it lists, as its doing a check these new blogs out first kinda thing. Importance thing. I tried to figure out why or how it was doing that but couldn't find anything. I think its a javascript thing, could be wrong, but its my guess. Does it bother you it does this?

**Comment by ldecicco-USGS** [comment]
I don't mind it...

**Comment by wdwatkins** [comment]
That's fine I think.  Multiple pages is fine if we get to that many posts.
