### ISSUE TITLE
Image sizes

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-OWI/owi-blog#23]
The default seems to be (at least) 100% width. I'd prefer to keep the native size of the images...or at least muck around with something even smarter.

**Comment by mwernimont** [comment]
@ldecicco-USGS #33 created a class that we can add to the images that we want side by side in the blog.  I have it coded that when it goes mobile the images go 100% so people on phones will be able to see the images still.

If this isn't possible to add the class to the images, just let me know. I chose this solution to avoid messing with the themes code too much and the headache that can create if you're trying to reinvent the wheel inside someone else's code.

**Comment by ldecicco-USGS** [comment]
So the R markdown files just make the side-by-side images like this:

```
<img src='/static/plotFlowConc/unnamed-chunk-2-1.png'/><img src='/static/plotFlowConc/unnamed-chunk-2-2.png'/>
```

What would I need to do to wrap them in that class? This?:
```
<div class="sideBySide">
   <img src='/static/plotFlowConc/unnamed-chunk-2-1.png'/>
   <img src='/static/plotFlowConc/unnamed-chunk-2-2.png'/>
</div>

When I tried that, I got the images stacked on top of each other:

http://dev-owi.usgs.gov-website.s3-website-us-west-2.amazonaws.com/blog/plotFlowConc/
```

**Comment by mwernimont** [comment]
<img class="sideBySide" src=""/>

for each one.Too much work? I guess I don't know how many you have that you want side by side

**Comment by mwernimont** [comment]
`<img class="sideBySide"/>`

Too much work that way?

**Comment by ldecicco-USGS** [comment]
I don't think that's too much work...might even be able to add that via the .Rmd file. But, I don't think it's doing it (as I've tried at least):
http://dev-owi.usgs.gov-website.s3-website-us-west-2.amazonaws.com/blog/plotFlowConc/

**Comment by mwernimont** [comment]
huh, it worked for me. Will look into it closer

**Comment by ldecicco-USGS** [comment]
Awesome
