### ISSUE TITLE
Category vs Tags

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-OWI/owi-blog#26]
Someone that understands this a bit better...could you have a look at the in-development blog, and see what we should be doing?

**Comment by jiwalker-usgs** [comment]
My understanding is that each post needs 1 and only 1 category, but any number of tags can apply to it.  I would say that we should perhaps switch the R category to USGS_R or even Data Science to refer to the source of the post and then tags with things such as R, water, storm, etc.

**Comment by ldecicco-USGS** [comment]
Makes sense to me
