### ISSUE TITLE
Blog ideas

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-OWI/owi-blog#3]
- [x] EGRET (randomized residuals)
- [ ] WaterWatch aka new stats feature in dataRetrieval
- [x] geoknife webgeom blog https://github.com/USGS-R/geoknife/issues/284#issuecomment-225276454

**Comment by ldecicco-USGS** [comment]
I'm hoping this is one of the first posts:

https://github.com/USGS-R/EGRET/blob/master/vignettes/rResid.Rmd

**Comment by wdwatkins** [comment]
Could make one once the stats service dataRetrieval stuff is done.  

Would the blog be a general place where we "market" new things we put out?  Or does something already serve that purpose (the twitter account?)?  In my experience the biggest barrier to getting people to use research tools is just knowing that they exist.

**Comment by ldecicco-USGS** [comment]
Absolutely. I was thinking of having you and @lindsaycarr  do a "WaterWatch" post...she'll probably know what I mean

**Comment by lindsaycarr** [comment]
Yeah, been wanting to do that! Map of current streamflow conditions across US: http://waterwatch.usgs.gov/?id=ww_current

**Comment by ldecicco-USGS** [comment]
I'd pick one state, but make that state the very first argument in the r code. I just spent a tiny amount of effort on it, and I don't think it will be easy to use `leaflet`, I think you'll have to just make a static map. Maybe someday we'll find a loophole that will let us use `leaflet` though...that would be cool.
