### ISSUE TITLE
Title/author relative font sizes

### ISSUE THREAD

**Issue by wdwatkins** [USGS-OWI/owi-blog#40]
Title and author font is currently the same size, which makes the author a bit too prominent.  Make the title bigger, author smaller or both.  Maybe have author same size as the date?

**Comment by mwernimont** [comment]
#43 @wdwatkins should take care of this

**Comment by wdwatkins** [comment]
Looks good:
![image](https://cloud.githubusercontent.com/assets/13987349/16591332/0a58a82e-42a1-11e6-8e1f-8e6773652ee9.png)
