### ISSUE TITLE
OWI Favicon

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-OWI/owi-blog#44]
Also, the OWI image in the upper-left header should probably direct to owi.usgs.gov

**Comment by jread-usgs** [comment]
or the root? so http://dev-owi.usgs.gov-website.s3-website-us-west-2.amazonaws.com/index.html and owi.usgs.gov/index.html on prod?

**Comment by ldecicco-USGS** [comment]
yeah, was going to set up another issue to try to straighten out the full paths and relative paths...

**Comment by mwernimont** [comment]
Uh..anyone know where one would put the link for a favicon in this file structure?

**Comment by ldecicco-USGS** [comment]
I think Hugo/static/img?

https://github.com/spf13/hugo/issues/143

**Comment by mwernimont** [comment]
Favicon added with this #47

**Comment by ldecicco-USGS** [comment]
The favicon is different than the owi site 
![2016-06-21_13-31-23](https://cloud.githubusercontent.com/assets/1105215/16241690/81839910-37b4-11e6-9e1e-48a66c30d6fa.png)

**Comment by mwernimont** [comment]
Yeah, I don't like the other favicon, will be changing it on the other site

**Comment by ldecicco-USGS** [comment]
I was going to say, I like this one better!
