### ISSUE TITLE
Create "test" bucket

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-OWI/owi-blog#51]
dev tier will include "--buildDrafts"
test tier will not

**Comment by jiwalker-usgs** [comment]
http://test-owi.usgs.gov-website.s3-website-us-west-2.amazonaws.com/blog/

also, set up a tab on Jenkins with all these jobs so you don't have to scroll to the o's

**Comment by ldecicco-USGS** [comment]
Awesome!
