### ISSUE TITLE
Existing blogs need alt tags + update creator/reviewer instructions

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-OWI/owi-blog#61]
idea from @jkreft-usgs 
- hey, something that you are going to dinged on from an accessabilty standpoint is alt-tags for images
```
Images
![alt text][id]
```
- using the AInspector Sidebar https://addons.mozilla.org/en-US/firefox/addon/ainspector-sidebar/
     - there are a few other notable things, some of which are harder than others.
     - alt tags for images
     - putting in a language tag
     - contrast, especially in the code blocks, is not high enough
     - There is no <main> tag to denote the primary content of the page
     - The big things are the language tag and the alt tags on images.
- @jiwalker-usgs: _It isn't just a one-time issue though, each post needs to handle this_
     - more of something that should be on a reviewer’s checklist or for travis to look for on a pull request
     - something like this for checking links in a markdown document http://blog.paracode.com/2015/09/16/using-travis-ci-to-validate-awesome-lists/
     - html-proofer
          - https://github.com/18F/html-proofer-docker
          - https://github.com/gjtorikian/html-proofer
          - html-proofer looks remarkably easy, actually

**Comment by ldecicco-USGS** [comment]
Added lang tag to theme, so that should be done for good. Added alt text to images via `fig.cap`.
