### ISSUE TITLE
Revisit code style

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-OWI/owi-blog#66]
The code style I think could still use some sprucing up. 

Take the code from the plotFlowConc post:

```r
library(EGRET)
library(ggplot2)

eList <-  Choptank_eList
Sample <- eList$Sample
INFO <- eList$INFO

Sample$cen <- factor(Sample$Uncen)
levels(Sample$cen) <- c("Censored","Uncensored") 

plotConcQ_gg <- ggplot(data=Sample) +
  geom_point(aes(x=Q, y=ConcAve, color = cen)) +
  scale_x_log10() +
  ggtitle(INFO$station.nm)

plotConcQ_gg
plotConcQ(eList)
```

Mirroring the above github style  would be my first vote. At a minimum, I think we need to improve the contrast.

**Comment by mwernimont** [comment]
What am I doing here @ldecicco-USGS ? I don't write code like this ever so not sure what I'm supposed to be doing?

**Comment by ldecicco-USGS** [comment]
Oh...I didn't mean use that code. I mean...look at the github style of the random code I pasted above. I'd like to emulate the github style (font color, background color, size, etc...) for our code snippets in the blogs. Currently, code snippets do not have enough contrast, and the font seems a little small.

**Comment by mwernimont** [comment]
Ah. I'll see what I can do!

**Comment by mwernimont** [comment]
PR for this here #69

**Comment by ldecicco-USGS** [comment]
Lookin' good. Can we make the size the same as the main text? It's a bit small for my aging eyes....and I'm not that old yet.
