### ISSUE TITLE
More style

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-OWI/owi-blog#8]
Below the posts are twitter and other icons. We need to figure out how to configure that stuff. Generally, we might want to pick a different theme. I'm not a huge fan of how the code is being styled. I'll try to get more specific the more I play.

**Comment by ldecicco-USGS** [comment]
Here are a few that seemed (in my opinion) worthy to look more into.

http://themes.gohugo.io/theme/greyshade/

http://themes.gohugo.io/theme/polymer

http://themes.gohugo.io/theme/hugo-minimalist/

http://themes.gohugo.io/theme/beautifulhugo/

http://themes.gohugo.io/theme/future-imperfect

http://themes.gohugo.io/theme/blackburn/

I think I'm going to pull in the last one (but anyone should feel free to weigh in on this), and see if I can inject the changes @mwernimont made to the default template...

**Comment by ldecicco-USGS** [comment]
FYI, I'm settling in on future-imperfect

**Comment by lindsaycarr** [comment]
Yeah, I like that one - it's a good mix between stylish/artsy and practical (where hugo-minimalist and polymer are more on the extremes of artsy and simple/practical)

**Comment by wdwatkins** [comment]
Seems like a good choice to me.

**Comment by wdwatkins** [comment]
Also, the post previews on the 'main screen' should be changed so they either don't preview the text or it looks nicer.  It is currently previewing code, and that makes it messy:
![image](https://cloud.githubusercontent.com/assets/13987349/16132335/4d47d2fe-33d8-11e6-9c2b-738a705b5647.png)
Removing it is covered in the quick start guide.  Don't think I ever got it work successfully though.

**Comment by ldecicco-USGS** [comment]
Yeah, I think we're at a state now that @mwernimont can have another crack at style upgrades.

**Comment by mwernimont** [comment]
I'm not against style upgrades, but next time can we decide these things before calling me in? Doing the work twice isn't very efficient.

**Comment by wdwatkins** [comment]
Yeah sorry about that Marty.  Forgot you were already working on the other theme.

**Comment by ldecicco-USGS** [comment]
I was mostly looking around for a theme that had the best documentation about the config file...now that I understand the config file a bit better, we can fairly easily swap back and forth (from *my* perspective) themes. But, yeah, our next step is absolutely nailing down that theme and sticking with it.
