### ISSUE TITLE
 weird word-wrapping

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-OWI/owi-blog#82]
@mwernimont 

Any idea why the last paragraph here:
http://dev-owi.usgs.gov-website.s3-website-us-west-2.amazonaws.com/blog/plotFlowConc/

has that weird word-wrapping going on again?

**Comment by ldecicco-USGS** [comment]
I added a new line between the paragraph and line above, and that seemed to fix it.

**Comment by mwernimont** [comment]
@ldecicco-USGS Do you need me to look at this since you reopened it?

**Comment by ldecicco-USGS** [comment]
Yeah (sorry got distracted). It keeps popping up, and would be good to figure out a way to make sure there are no instances where that wrapping occurs. At the bottom of this page now, it's happening again:

http://dev-owi.usgs.gov-website.s3-website-us-west-2.amazonaws.com/blog/plotFlowConc/

**Comment by mwernimont** [comment]
#89 Should fix it
