### ISSUE TITLE
easily share the blog posts on social media

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-OWI/owi-blog#97]
We cannot use [AddThis](http://www.addthis.com/), but DOI has a workaround on GitHub: [github.com/usinterior/ncshare](https://github.com/usinterior/ncshare). This might actually be something that goes into the [USGSmarkdowntemplates](https://github.com/USGS-R/USGSmarkdowntemplates) repo. 

@ldecicco-USGS what do you think?

**Comment by ldecicco-USGS** [comment]
I'd guess that would be more appropriate in the actual Hugo template. I'll have a look later. I don't think our sharing buttons were from AddThis, do you?

**Comment by lindsaycarr** [comment]
They were not, but I didn't think we had any sharing buttons. An email about not being able to use AddThis is what sparked this thought in the first place, that's why I included that

**Comment by ldecicco-USGS** [comment]
They are down at the bottom, just the default that comes with Hugo. The image icons in the link you shared does look a bit prettier, it probably wouldn't be too hard to swap out.

**Comment by ldecicco-USGS** [comment]
What we have now:
![2016-08-15_10-36-36](https://cloud.githubusercontent.com/assets/1105215/17669684/2f29545c-62d4-11e6-83b5-6d9db1c60871.png)

**Comment by lindsaycarr** [comment]
Oh wow, did not notice those before. I like them! I wonder if there is a way to include them at the top as well? Others might not notice them down at the bottom just as I did not.

So this task could be for @mwernimont to just include the Hugo sharing icons at the top?

**Comment by ldecicco-USGS** [comment]
@mwernimont can you take a look at the ncshare and see if it's something you could replace the current Hugo "sharing" script? @jiwalker-usgs would we also want (need?) to use in the vizlab package?
